# Generated by Django 5.1 on 2026-06-11 14:13

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthCenter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "center_type",
                    models.CharField(
                        choices=[
                            ("hospital_publico", "Hospital publico"),
                            ("cesfam", "Cesfam"),
                            ("clinica_privada", "Clinica privada"),
                            ("farmacia", "Farmacia"),
                            ("urgencia", "Urgencia"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("comuna", models.CharField(blank=True, max_length=100, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "services",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={
                "db_table": "health_centers",
                "managed": False,
            },
        ),
    ]
