# Generated by Django 5.1 on 2026-06-11 04:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tittle", models.CharField(max_length=255)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("exam", "Exam"),
                            ("prescription", "Prescription"),
                            ("sick_leave", "Sick leave"),
                            ("report", "Report"),
                            ("vaccine", "Vaccine"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("file_key", models.CharField(max_length=255)),
                ("file_url", models.CharField(blank=True, max_length=500, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=255, null=True)),
                ("file_size_bytes", models.IntegerField(blank=True, null=True)),
                ("document_date", models.DateField(blank=True, null=True)),
                (
                    "issuing_profesional",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ai_metada", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "documents",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "document_categories",
                "managed": False,
            },
        ),
    ]
